export const LOAD_PRODUCTS = "LOAD_PRODUCTS";
export const LOAD_CUSTOMER = "LOAD_CUSTOMER";
export const SEARCH_OR_HIGHLIGT_TEXT = "SEARCH_OR_HIGHLIGT_TEXT";
export const SET_SEARCH_MODE = "SET_SEARCH_MODE";